name: pokedex_poyectfinal
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.8
  http: ^1.1.0
  provider: ^6.1.1
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/pokeball.png
    - assets/pokeballblack.png
    - assets/pokedex.png
    - assets/alturaicon.png
    - assets/pesoicon.png
    - assets/pokeball2.png
    - assets/loading/pokeball.gif
    - assets/loading/loading-pokeball.gif
    - assets/icon_types/normal.png
    - assets/icon_types/fire.png
    - assets/icon_types/water.png
    - assets/icon_types/electric.png
    - assets/icon_types/grass.png
    - assets/icon_types/ice.png
    - assets/icon_types/fighting.png
    - assets/icon_types/poison.png
    - assets/icon_types/ground.png
    - assets/icon_types/flying.png
    - assets/icon_types/psychic.png
    - assets/icon_types/bug.png
    - assets/icon_types/rock.png
    - assets/icon_types/ghost.png
    - assets/icon_types/dark.png
    - assets/icon_types/steel.png
    - assets/icon_types/fairy.png
    - assets/icon_types/dragon.png

  uses-material-design: true